# Setup
title: Dev Blog
description: 후쿠오카에서 살고 있는 프론트앤드 취준생입니당
url: https://topgun0415.github.io
avatar: /profile.png
paginate: 5
permalink: pretty
cover_image: /background.gif

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Philip Lee
  links:
    - https://www.instagram.com/philipuuu/
    - https://topgun0415.github.io
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Philip Lee
  url: https://topgun0415.github.io
  email: topgun920415@gmail.com
